// Code generated by Kitex v0.7.0. DO NOT EDIT.

package internalfavoriteservice

import (
	server "github.com/cloudwego/kitex/server"
	favorite "tiktok/hertz-server/kitex_gen/douyin/favorite"
)

// NewInvoker creates a server.Invoker with the given handler and options.
func NewInvoker(handler favorite.InternalFavoriteService, opts ...server.Option) server.Invoker {
	var options []server.Option

	options = append(options, opts...)

	s := server.NewInvoker(options...)
	if err := s.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	if err := s.Init(); err != nil {
		panic(err)
	}
	return s
}
