// Code generated by Kitex v0.7.0. DO NOT EDIT.

package internalcommentservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	comment "tiktok/hertz-server/kitex_gen/douyin/comment"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	InternalActionComment(ctx context.Context, request *comment.InternalActionCommentRequest, callOptions ...callopt.Option) (r *comment.InternalActionCommentResponse, err error)
	InternalListComment(ctx context.Context, request *comment.InternalListCommentRequest, callOptions ...callopt.Option) (r *comment.InternalListCommentResponse, err error)
	InternalCountComment(ctx context.Context, request *comment.InternalCountCommentRequest, callOptions ...callopt.Option) (r *comment.InternalCountCommentResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kInternalCommentServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kInternalCommentServiceClient struct {
	*kClient
}

func (p *kInternalCommentServiceClient) InternalActionComment(ctx context.Context, request *comment.InternalActionCommentRequest, callOptions ...callopt.Option) (r *comment.InternalActionCommentResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.InternalActionComment(ctx, request)
}

func (p *kInternalCommentServiceClient) InternalListComment(ctx context.Context, request *comment.InternalListCommentRequest, callOptions ...callopt.Option) (r *comment.InternalListCommentResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.InternalListComment(ctx, request)
}

func (p *kInternalCommentServiceClient) InternalCountComment(ctx context.Context, request *comment.InternalCountCommentRequest, callOptions ...callopt.Option) (r *comment.InternalCountCommentResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.InternalCountComment(ctx, request)
}
